
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jul 23 21:16:58 KST 2012
//----------------------------------------------------

package name.sccu.scope;

/** CUP generated interface containing symbol constants. */
public interface ScopeSym {
  /* terminals */
  public static final int NUM = 3;
  public static final int LBRACE = 6;
  public static final int STATIC = 13;
  public static final int PUBLIC = 11;
  public static final int PKG = 9;
  public static final int SEMI = 4;
  public static final int EQUAL = 8;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int ID = 10;
  public static final int DOT = 5;
  public static final int error = 1;
  public static final int PRIVATE = 12;
  public static final int RBRACE = 7;
  public static final int CLASS = 14;
}

