
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 18 00:18:06 KST 2012
//----------------------------------------------------

package name.sccu.scope;

/** CUP generated interface containing symbol constants. */
public interface ScopeSym {
  /* terminals */
  public static final int num = 3;
  public static final int error = 1;
  public static final int SEMI = 4;
  public static final int EOF = 0;
  public static final int plus = 2;
}

