
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 11 00:21:43 KST 2012
//----------------------------------------------------

package name.sccu.scope;

/** CUP generated interface containing symbol constants. */
public interface ScopeSym {
  /* terminals */
  public static final int error = 1;
  public static final int ANY = 2;
  public static final int EOF = 0;
}

