
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 18 00:18:06 KST 2012
//----------------------------------------------------

package name.sccu.scope;

import java_cup.runtime.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed Jul 18 00:18:06 KST 2012
  */
public class ScopeCup extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public ScopeCup() {super();}

  /** Constructor which sets the default scanner. */
  public ScopeCup(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ScopeCup(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\005\000\002\004\002\000\002\003\005\000\002\002" +
    "\004\000\002\002\005\000\002\002\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\011\000\004\005\001\001\002\000\004\005\010\001" +
    "\002\000\004\002\006\001\002\000\004\002\uffff\001\002" +
    "\000\006\004\012\006\011\001\002\000\006\004\ufffd\006" +
    "\ufffd\001\002\000\004\002\000\001\002\000\004\005\010" +
    "\001\002\000\006\004\ufffe\006\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\011\000\006\003\004\004\003\001\001\000\004\002" +
    "\006\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\002" +
    "\012\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ScopeCup$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ScopeCup$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ScopeCup$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 2;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$ScopeCup$actions {



  private final ScopeCup parser;

  /** Constructor */
  CUP$ScopeCup$actions(ScopeCup parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$ScopeCup$do_action(
    int                        CUP$ScopeCup$act_num,
    java_cup.runtime.lr_parser CUP$ScopeCup$parser,
    java.util.Stack            CUP$ScopeCup$stack,
    int                        CUP$ScopeCup$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ScopeCup$result;

      /* select the action based on the action number */
      switch (CUP$ScopeCup$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // EXPR ::= num 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.peek()).right;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$ScopeCup$stack.peek()).value;
		 RESULT = new Double(((Double)n).doubleValue()); 
              CUP$ScopeCup$result = parser.getSymbolFactory().newSymbol("EXPR",0, ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.peek()), RESULT);
            }
          return CUP$ScopeCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // EXPR ::= EXPR plus EXPR 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.elementAt(CUP$ScopeCup$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.elementAt(CUP$ScopeCup$top-2)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$ScopeCup$stack.elementAt(CUP$ScopeCup$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.peek()).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$ScopeCup$stack.peek()).value;
		 RESULT = new Double(((Double)e1).doubleValue() + ((Double)e2).doubleValue()); 
              CUP$ScopeCup$result = parser.getSymbolFactory().newSymbol("EXPR",0, ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.elementAt(CUP$ScopeCup$top-2)), ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.peek()), RESULT);
            }
          return CUP$ScopeCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // $START ::= EXPR_LIST EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.elementAt(CUP$ScopeCup$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.elementAt(CUP$ScopeCup$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ScopeCup$stack.elementAt(CUP$ScopeCup$top-1)).value;
		RESULT = start_val;
              CUP$ScopeCup$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.elementAt(CUP$ScopeCup$top-1)), ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ScopeCup$parser.done_parsing();
          return CUP$ScopeCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // EXPR_LIST ::= NT$0 EXPR SEMI 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$ScopeCup$stack.elementAt(CUP$ScopeCup$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.elementAt(CUP$ScopeCup$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.elementAt(CUP$ScopeCup$top-1)).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$ScopeCup$stack.elementAt(CUP$ScopeCup$top-1)).value;
		 RESULT = new Double(((Double)e).doubleValue()); 
              CUP$ScopeCup$result = parser.getSymbolFactory().newSymbol("EXPR_LIST",1, ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.elementAt(CUP$ScopeCup$top-2)), ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.peek()), RESULT);
            }
          return CUP$ScopeCup$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // NT$0 ::= 
            {
              Object RESULT =null;
 System.out.println("start parsing"); 
              CUP$ScopeCup$result = parser.getSymbolFactory().newSymbol("NT$0",2, ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.peek()), ((java_cup.runtime.Symbol)CUP$ScopeCup$stack.peek()), RESULT);
            }
          return CUP$ScopeCup$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

